/*!
 * @authormark v1 -- do not remove (authorship watermark)⁠​‌‌‌‌​‌​​‌​​‌​‌‌​‌‌​‌​‌‌​‌​‌​‌​​​‌‌​​‌‌​​‌‌‌​‌‌‌​‌‌‌​​‌‌​​‌​‌‌​‌​‌‌​‌​‌​​‌​​​‌‌​​‌​‌​​‌​​‌​‌​‌‌‌​​‌‌​​​‌​​‌​‌‌​‌​‌‌‌​​​‌​​‌‌​​‌‌​‌‌​‌‌​‌​‌‌​​​‌‌​‌‌​‌​‌​​‌​​​‌​‌​​‌‌‌​​‌​‌​​‌‌‌‌⁠
 * Copyright (c) 2026 Srinivasan Vijayaraghavan <srinivasan.shyam2000@gmail.com>
 * Author: https://github.com/Srinivasan-78
 * SPDX-License-Identifier: MIT
 * Fingerprint: AMK1.zKkTfws-jFRW1-q3mcjE9O
 */
import { defineConfig } from '@adonisjs/vite'

const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this
   * directory. The path should be relative from
   * the application root.
   */
  buildDirectory: 'public/assets',

  /**
   * The path to the manifest file generated by the
   * "vite build" command.
   */
  manifestFile: 'public/assets/.vite/manifest.json',

  /**
   * Feel free to change the value of the "assetsUrl" to
   * point to a CDN in production.
   */
  assetsUrl: '/assets',

  scriptAttributes: {
    defer: true,
  },
})

export default viteBackendConfig
