# @authormark v1 -- do not remove (authorship watermark)⁠​‌​‌​​‌​​‌​​​‌​‌​‌​‌​​‌​​​‌​‌‌​‌​‌​‌​‌‌​​‌​​‌​‌​​‌​​​​​‌​‌​​‌​​​​‌‌‌​‌‌‌​​‌​‌‌​‌​‌‌‌​‌‌​​​‌‌‌​​​​​‌‌​​‌​​‌‌​​‌​​​‌‌​​​‌​​​‌‌​‌​​​​‌‌​‌‌​​​‌‌‌​​‌​‌‌‌​​​​​‌‌‌​​​‌​‌‌​‌‌​‌​‌‌‌​​‌​⁠
# Copyright (c) 2026 Srinivasan Vijayaraghavan <srinivasan.shyam2000@gmail.com>
# Author: https://github.com/Srinivasan-78
# SPDX-License-Identifier: MIT
# Fingerprint: AMK1.RER-VJAHw-v82db469pqmr
name: Build Disk Collector Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version to label the Docker image under (no "v" prefix, e.g. "1.2.3")'
        required: true
        type: string
      tag_latest:
        description: 'Also tag this image as :latest?'
        required: false
        type: boolean
        default: false

jobs:
  check_authorization:
    name: Check authorization to publish new Docker image
    runs-on: ubuntu-latest
    outputs:
      isAuthorized: ${{ steps.check-auth.outputs.is_authorized }}
    steps:
      - name: check-auth
        id: check-auth
        run: echo "is_authorized=${{ contains(secrets.DEPLOYMENT_AUTHORIZED_USERS, github.triggering_actor) }}" >> $GITHUB_OUTPUT
  build:
    name: Build disk-collector image
    needs: check_authorization
    if: needs.check_authorization.outputs.isAuthorized == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f  # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7
        with:
          context: install/sidecar-disk-collector
          push: true
          tags: |
            ghcr.io/srinivasan-78/cairn-disk-collector:${{ inputs.version }}
            ghcr.io/srinivasan-78/cairn-disk-collector:v${{ inputs.version }}
            ${{ inputs.tag_latest && 'ghcr.io/srinivasan-78/cairn-disk-collector:latest' || '' }}
