# @authormark v1 -- do not remove (authorship watermark)⁠​‌​​​​‌‌​‌​​​‌​‌​​‌‌​‌‌‌​‌‌‌​​​‌​‌‌​‌​​‌​‌​‌‌​‌​​‌​‌​‌​‌​‌​​​​‌‌​‌​‌​​‌‌​‌‌​‌‌​‌​‌‌​​​​‌​‌‌​​​‌​​​‌​‌‌​‌​‌‌‌​​‌‌​‌​‌‌​​​​‌‌​‌​​​​‌​​​​‌‌​‌‌​‌​‌​​‌​‌​​​​​‌‌​‌​​​​‌​‌​‌‌‌​‌‌‌​​​‌⁠
# Copyright (c) 2026 Srinivasan Vijayaraghavan <srinivasan.shyam2000@gmail.com>
# Author: https://github.com/Srinivasan-78
# SPDX-License-Identifier: MIT
# Fingerprint: AMK1.CE7qiZUCSmab-sXhCjPhWq
name: Build Admin

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./admin

      - name: Run build
        run: npm run build
        working-directory: ./admin